server:
  port: 8080

spring:
  application:
    name: restful-api-example
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

logging:
  level:
    com.example.template: DEBUG
    org.springframework.web: INFO
